receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
  memory_limiter:
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
extensions:
  zpages: {}
exporters:
  # Original ClickHouse exporter for OpenLIT UI
  clickhouse:
    endpoint: tcp://${env:INIT_DB_HOST}:${env:INIT_DB_PORT}?dial_timeout=10s
    database: ${env:INIT_DB_DATABASE}
    username: ${env:INIT_DB_USERNAME}
    password: ${env:INIT_DB_PASSWORD}
    ttl: 730h
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
      
  # Prometheus exporter for metrics (connects to separate docker-compose)
  prometheusremotewrite:
    endpoint: "http://host.docker.internal:9090/api/v1/write"
    add_metric_suffixes: false
    
  # Tempo exporter for traces (connects to separate docker-compose)  
  otlp:
    endpoint: "host.docker.internal:14317"
    tls:
      insecure: true
service:
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ clickhouse ]
    traces:
      receivers: [ otlp ]
      processors: [memory_limiter, batch]
      exporters: [ clickhouse, otlp ]
    metrics:
      receivers: [ otlp ]
      processors: [memory_limiter, batch]
      exporters: [ clickhouse, prometheusremotewrite ]